# Generated by Django 4.2.9 on 2024-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_de_cambio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
    ]
